#!/bin/bash
###############################################################################
# CallFlow — One-command deployment script for Ubuntu 24.04 VPS
#
# Usage (on your VPS):
#   cd /path/to/Call_Flow
#   chmod +x deploy.sh
#   ./deploy.sh
#
# Prerequisites:
#   - Node.js 20+ installed
#   - PostgreSQL running with DATABASE_URL configured in server/.env
#   - Nginx installed and configured (see below for auto-setup option)
#   - PM2 installed globally: npm i -g pm2
#
# What this script does:
#   1. Pulls latest code from git
#   2. Installs all dependencies (root + server)
#   3. Runs Prisma migrations (push) and generates client
#   4. Seeds the admin user (idempotent upsert)
#   5. Builds the frontend (Vite → dist/)
#   6. Builds the backend (TypeScript → server/dist/)
#   7. Restarts PM2 process
#   8. Optionally configures Nginx (first-time only)
###############################################################################
set -euo pipefail

# ─── Configuration ───────────────────────────────────────────────────────────
APP_DIR="$(cd "$(dirname "$0")" && pwd)"
SERVER_DIR="$APP_DIR/server"
PM2_APP_NAME="callflow-api"
NGINX_CONF="/etc/nginx/sites-available/callflow"
NGINX_ENABLED="/etc/nginx/sites-enabled/callflow"

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  🚀 CallFlow Deployment"
echo "═══════════════════════════════════════════════════════════"
echo ""

# ─── Step 1: Pull latest code ────────────────────────────────────────────────
echo "📥 Step 1/7: Pulling latest code from Git..."
cd "$APP_DIR"
git pull --ff-only origin main 2>/dev/null || git pull --ff-only origin master 2>/dev/null || {
  echo "⚠️  Git pull failed. Continuing with current code..."
}
echo "   ✅ Code updated"
echo ""

# ─── Step 2: Install dependencies ───────────────────────────────────────────
echo "📦 Step 2/7: Installing dependencies..."
cd "$APP_DIR"
npm ci --omit=dev 2>/dev/null || npm install
cd "$SERVER_DIR"
npm ci 2>/dev/null || npm install
echo "   ✅ Dependencies installed"
echo ""

# ─── Step 3: Database setup ─────────────────────────────────────────────────
echo "🗄️  Step 3/7: Database migrations & Prisma client..."
cd "$SERVER_DIR"

# Check that .env exists
if [ ! -f ".env" ]; then
  echo "   ❌ ERROR: server/.env not found!"
  echo "   Copy server/.env.example to server/.env and configure it."
  exit 1
fi

npx prisma generate
npx prisma db push --accept-data-loss 2>/dev/null || npx prisma db push
echo "   ✅ Database schema synced"

# Seed admin user (idempotent upsert, safe to run every deploy)
npx tsx prisma/seed.ts 2>/dev/null && echo "   ✅ Admin seed complete" || echo "   ⚠️  Seed skipped (may already exist)"
echo ""

# ─── Step 4: Build frontend ─────────────────────────────────────────────────
echo "🎨 Step 4/7: Building frontend (Vite)..."
cd "$APP_DIR"
npm run build
echo "   ✅ Frontend built → dist/"
echo ""

# ─── Step 5: Build backend ──────────────────────────────────────────────────
echo "⚙️  Step 5/7: Building backend (TypeScript)..."
cd "$SERVER_DIR"
npm run build
echo "   ✅ Backend built → server/dist/"
echo ""

# ─── Step 6: Restart PM2 ────────────────────────────────────────────────────
echo "🔄 Step 6/7: Restarting PM2 process..."
cd "$APP_DIR"

# Check if PM2 process exists
if pm2 describe "$PM2_APP_NAME" > /dev/null 2>&1; then
  pm2 restart "$PM2_APP_NAME"
  echo "   ✅ PM2 process restarted"
else
  echo "   ℹ️  PM2 process not found, starting fresh..."
  pm2 start server/ecosystem.config.cjs --env production
  pm2 save
  echo "   ✅ PM2 process started and saved"
fi
echo ""

# ─── Step 7: Nginx check ────────────────────────────────────────────────────
echo "🌐 Step 7/7: Checking Nginx configuration..."

if [ -f "$NGINX_CONF" ]; then
  echo "   ✅ Nginx config already exists"
else
  echo "   ℹ️  No Nginx config found. Creating default config..."
  
  # Detect the server IP
  SERVER_IP=$(hostname -I | awk '{print $1}')
  
  sudo tee "$NGINX_CONF" > /dev/null <<NGINX_EOF
# CallFlow — auto-generated by deploy.sh
server {
    listen 80;
    server_name ${SERVER_IP};

    root ${APP_DIR}/dist;
    index index.html;

    # API proxy → Node.js backend on port 3001
    location /api/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # WebSocket proxy → Node.js backend
    location /socket.io/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
    }

    # SPA fallback — serves index.html for all frontend routes
    location / {
        try_files \$uri \$uri/ /index.html;
    }
}
NGINX_EOF

  # Enable the site
  sudo ln -sf "$NGINX_CONF" "$NGINX_ENABLED" 2>/dev/null || true
  
  # Remove default nginx site if it conflicts
  sudo rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
  
  # Test and reload nginx
  sudo nginx -t && sudo systemctl reload nginx
  echo "   ✅ Nginx configured and reloaded"
fi

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  ✅ Deployment complete!"
echo ""
echo "  Frontend:  http://${SERVER_IP:-your-server-ip}"
echo "  API:       http://${SERVER_IP:-your-server-ip}/api/health"
echo "  PM2 logs:  pm2 logs $PM2_APP_NAME"
echo "  PM2 status: pm2 status"
echo "═══════════════════════════════════════════════════════════"
echo ""
